[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/shorten"
  to = "/.netlify/functions/shorten"
  status = 200

[[redirects]]
  from = "/:shortUrl"
  to = "/.netlify/functions/redirect/:shortUrl"
  status = 200
